apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  backoffLimit: {{ backoffLimit }}
  activeDeadlineSeconds: {{ activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        task: {{ container_name }}
        username: {{ username }}
    spec:
      hostNetwork: {{ hostNetwork }}
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-auth-job
      volumes:
      - name: config-volume
        configMap:
          name: {{ configmap_name }}
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: {{ pvc_name }}
      - name: desarchive-volume
        readOnly: true
        hostPath:
          path: {{ desarchiveHostPath }}
      - name: coadd-volume
        readOnly: true
        hostPath:
          path: {{ coaddHostPath }}
      - name: dr2-tiles
        readOnly: true
        hostPath:
          path: {{ dr2TilePath }}
      initContainers:
      - name: init
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        image: busybox@sha256:edafc0a0fb057813850d1ba44014914ca02d671ae247107ca70c94db686e7de6
        command: ['/bin/sh', '-c', 'chown {{ uid }}:{{ gid }} /home/worker/output']
        volumeMounts:
        - name: persistent-volume
          mountPath: /home/worker/output
          subPath: {{ username }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: task
                  operator: In
                  values:
                  - {{ container_name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ container_name }}
        securityContext:
          runAsUser: {{ uid }}
          runAsGroup: {{ gid }}
        image: {{ image }}
        imagePullPolicy: {{ imagePullPolicy }}
        command: {{ command }}
        volumeMounts:
        - name: config-volume
          mountPath: '/home/worker/configjob.yaml'
          subPath: 'configjob.yaml'
        - name: persistent-volume
          mountPath: '/home/worker/output'
          subPath: {{ username }}
        - name: desarchive-volume
          mountPath: '/des003/desarchive'
        - name: coadd-volume
          mountPath: '/des004/coadd'
        - name: dr2-tiles
          mountPath: "/tiles/dr2"
        lifecycle:
          postStart:
            exec:
              command: ["python3", "init.py"]
          preStop:
            exec:
              command: ["python3", "prestop.py"]
        resources:
          limits:
            cpu: {{ resource_limit_cpu | quote }}
            memory: {{ resource_limit_memory | quote }}
          requests:
            cpu: {{ resource_request_cpu | quote }}
            memory: {{ resource_request_memory | quote }}
