apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  backoffLimit: {{ backoffLimit }}
  activeDeadlineSeconds: {{ activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-auth
      volumes:
      - name: config-volume
        configMap:
          name: {{ configmap_name }}
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: {{ pvc_name }}
      initContainers:
      - name: init
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        image: busybox@sha256:edafc0a0fb057813850d1ba44014914ca02d671ae247107ca70c94db686e7de6
        command: ['/bin/sh', '-c', 'chown -R 1001:1001 /home/worker/output']
        volumeMounts:
        - name: persistent-volume
          mountPath: /home/worker/output
          subPath: {{ username }}
      containers:
      - name: {{ container_name }}
        image: {{ image }}
        command: {{ command }}
        volumeMounts:
        - name: config-volume
          mountPath: '/home/worker/configjob.yaml'
          subPath: 'configjob.yaml'
        - name: persistent-volume
          mountPath: '/home/worker/output'
          subPath: {{ username }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", 'echo "$(date): Hello from the postStart handler" >> /home/worker/output/lifecycle_hook_test.log']
